#Ultima imagen de ububtu
FROM ubuntu:latest

# Instalamos Python3, pip3, Flask y actualizamos apt
RUN apt-get update && apt-get upgrade -y && \
apt-get install -y python3 python3-pip && \
rm /usr/lib/python*/EXTERNALLY-MANAGED && \
pip3 install Flask

# Para usar /app como directorio de trabajo
WORKDIR /app

# Para copiar el archivo de python (api.py) a la imagen de docker
COPY api.py /app/api.py

# Para que se ejecute en este puerto
EXPOSE 5252

# Sirve para ejecutar la aplicacion de Flask
CMD ["python3", "api.py"]
